
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."tbl_allowed_domains" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "domain" "text" NOT NULL
);

ALTER TABLE "public"."tbl_allowed_domains" OWNER TO "postgres";

ALTER TABLE "public"."tbl_allowed_domains" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_allowed_domains_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_checklist_productlists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_checklist" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "amount" integer NOT NULL,
    "final_price" real NOT NULL
);

ALTER TABLE "public"."tbl_checklist_productlists" OWNER TO "postgres";

ALTER TABLE "public"."tbl_checklist_productlists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_checklist_productlists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_checklists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_patient" bigint NOT NULL,
    "id_doctor" bigint NOT NULL,
    "id_user" bigint NOT NULL,
    "status" smallint NOT NULL
);

ALTER TABLE "public"."tbl_checklists" OWNER TO "postgres";

ALTER TABLE "public"."tbl_checklists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_checklists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_companies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "company" "text" NOT NULL
);

ALTER TABLE "public"."tbl_companies" OWNER TO "postgres";

ALTER TABLE "public"."tbl_companies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_companies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_doctors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "doctor" "text" NOT NULL
);

ALTER TABLE "public"."tbl_doctors" OWNER TO "postgres";

ALTER TABLE "public"."tbl_doctors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_doctors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_imported" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "doctor" "text" NOT NULL,
    "patient" "text" NOT NULL,
    "date" "date" NOT NULL,
    "value" real NOT NULL,
    "health_insurance" "text" NOT NULL,
    "description" "text" NOT NULL,
    "month" smallint NOT NULL,
    "year" smallint NOT NULL,
    "payment_method" smallint,
    "card_fee" real
);

ALTER TABLE "public"."tbl_imported" OWNER TO "postgres";

ALTER TABLE "public"."tbl_imported" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_imported_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_inventory" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "type" smallint NOT NULL,
    "amount" integer NOT NULL,
    "reason" smallint NOT NULL
);

ALTER TABLE "public"."tbl_inventory" OWNER TO "postgres";

ALTER TABLE "public"."tbl_inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_patients" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "patient" "text" NOT NULL
);

ALTER TABLE "public"."tbl_patients" OWNER TO "postgres";

ALTER TABLE "public"."tbl_patients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_patients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_percentages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "administration" real NOT NULL,
    "basic_taxes" "jsonb"[]
);

ALTER TABLE "public"."tbl_percentages" OWNER TO "postgres";

ALTER TABLE "public"."tbl_percentages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_percentages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_percentages" bigint NOT NULL,
    "product" "text" NOT NULL,
    "type" smallint NOT NULL,
    "unit" "text" NOT NULL,
    "base_price" real NOT NULL,
    "minimum" integer NOT NULL,
    "purchase" integer NOT NULL
);

ALTER TABLE "public"."tbl_products" OWNER TO "postgres";

ALTER TABLE "public"."tbl_products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_purchases" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "id_company" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "amount" integer NOT NULL,
    "price" real NOT NULL,
    "taxes" "jsonb"
);

ALTER TABLE "public"."tbl_purchases" OWNER TO "postgres";

ALTER TABLE "public"."tbl_purchases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_purchases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_user" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "user" "text" NOT NULL
);

ALTER TABLE "public"."tbl_user" OWNER TO "postgres";

ALTER TABLE "public"."tbl_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."tbl_allowed_domains"
    ADD CONSTRAINT "tbl_allowed_domains_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "tbl_checklist_productlists_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "tbl_checklists_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_companies"
    ADD CONSTRAINT "tbl_companies_company_key" UNIQUE ("company");

ALTER TABLE ONLY "public"."tbl_companies"
    ADD CONSTRAINT "tbl_companies_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_doctors"
    ADD CONSTRAINT "tbl_doctors_doctor_key" UNIQUE ("doctor");

ALTER TABLE ONLY "public"."tbl_doctors"
    ADD CONSTRAINT "tbl_doctors_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_imported"
    ADD CONSTRAINT "tbl_imported_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_imported"
    ADD CONSTRAINT "tbl_imported_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_inventory"
    ADD CONSTRAINT "tbl_inventory_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_patients"
    ADD CONSTRAINT "tbl_patients_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_percentages"
    ADD CONSTRAINT "tbl_percentages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_products"
    ADD CONSTRAINT "tbl_products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_purchases"
    ADD CONSTRAINT "tbl_purchases_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_user"
    ADD CONSTRAINT "tbl_user_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_user"
    ADD CONSTRAINT "tbl_user_id_user_key" UNIQUE ("id_user");

ALTER TABLE ONLY "public"."tbl_user"
    ADD CONSTRAINT "tbl_user_pkey" PRIMARY KEY ("id");

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_allowed_domains" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_checklist_productlists" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_checklists" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_companies" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_doctors" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_imported" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_inventory" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_patients" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_percentages" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_products" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_purchases" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_user" TO "authenticated" USING (true);

ALTER TABLE "public"."tbl_allowed_domains" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_checklist_productlists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_checklists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_companies" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_doctors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_imported" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_inventory" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_patients" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_percentages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_products" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_purchases" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_user" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "anon";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "anon";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_checklists" TO "anon";
GRANT ALL ON TABLE "public"."tbl_checklists" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_checklists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_companies" TO "anon";
GRANT ALL ON TABLE "public"."tbl_companies" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_companies" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_doctors" TO "anon";
GRANT ALL ON TABLE "public"."tbl_doctors" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_doctors" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_imported" TO "anon";
GRANT ALL ON TABLE "public"."tbl_imported" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_imported" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_inventory" TO "anon";
GRANT ALL ON TABLE "public"."tbl_inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_inventory" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_patients" TO "anon";
GRANT ALL ON TABLE "public"."tbl_patients" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_patients" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_percentages" TO "anon";
GRANT ALL ON TABLE "public"."tbl_percentages" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_percentages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_products" TO "anon";
GRANT ALL ON TABLE "public"."tbl_products" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_purchases" TO "anon";
GRANT ALL ON TABLE "public"."tbl_purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_purchases" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_user" TO "anon";
GRANT ALL ON TABLE "public"."tbl_user" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_user" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;

--
-- Dumped schema changes for auth and storage
--

