
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."tbl_allowed_domains" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "domain" "text" NOT NULL
);

ALTER TABLE "public"."tbl_allowed_domains" OWNER TO "postgres";

ALTER TABLE "public"."tbl_allowed_domains" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_allowed_domains_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_checklist_productlists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_checklist" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "amount" integer NOT NULL,
    "final_price" real NOT NULL
);

ALTER TABLE "public"."tbl_checklist_productlists" OWNER TO "postgres";

ALTER TABLE "public"."tbl_checklist_productlists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_checklist_productlists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_checklists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_patient" bigint NOT NULL,
    "id_doctor" bigint NOT NULL,
    "id_user" bigint NOT NULL,
    "status" smallint NOT NULL
);

ALTER TABLE "public"."tbl_checklists" OWNER TO "postgres";

ALTER TABLE "public"."tbl_checklists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_checklists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_companies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "company" "text" NOT NULL
);

ALTER TABLE "public"."tbl_companies" OWNER TO "postgres";

ALTER TABLE "public"."tbl_companies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_companies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_doctors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "doctor" "text" NOT NULL
);

ALTER TABLE "public"."tbl_doctors" OWNER TO "postgres";

ALTER TABLE "public"."tbl_doctors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_doctors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_imported" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "doctor" "text" NOT NULL,
    "patient" "text" NOT NULL,
    "date" "date" NOT NULL,
    "value" real NOT NULL,
    "health_insurance" "text" NOT NULL,
    "description" "text" NOT NULL,
    "month" smallint NOT NULL,
    "year" smallint NOT NULL,
    "payment_method" smallint,
    "card_fee" real
);

ALTER TABLE "public"."tbl_imported" OWNER TO "postgres";

ALTER TABLE "public"."tbl_imported" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_imported_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_inventory" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "type" smallint NOT NULL,
    "amount" integer NOT NULL,
    "reason" smallint NOT NULL
);

ALTER TABLE "public"."tbl_inventory" OWNER TO "postgres";

ALTER TABLE "public"."tbl_inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_patients" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "patient" "text" NOT NULL
);

ALTER TABLE "public"."tbl_patients" OWNER TO "postgres";

ALTER TABLE "public"."tbl_patients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_patients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_percentages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "administration" real NOT NULL,
    "basic_taxes" "jsonb"[]
);

ALTER TABLE "public"."tbl_percentages" OWNER TO "postgres";

ALTER TABLE "public"."tbl_percentages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_percentages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_percentages" bigint NOT NULL,
    "product" "text" NOT NULL,
    "type" smallint NOT NULL,
    "unit" "text" NOT NULL,
    "base_price" real NOT NULL,
    "amount" integer NOT NULL,
    "minimum" integer NOT NULL,
    "purchase" integer NOT NULL
);

ALTER TABLE "public"."tbl_products" OWNER TO "postgres";

ALTER TABLE "public"."tbl_products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_purchases" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "id_company" bigint NOT NULL,
    "id_product" bigint NOT NULL,
    "amount" integer NOT NULL,
    "price" real NOT NULL,
    "taxes" "jsonb"[]
);

ALTER TABLE "public"."tbl_purchases" OWNER TO "postgres";

ALTER TABLE "public"."tbl_purchases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_purchases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_rbac_functions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "function" "text" NOT NULL
);

ALTER TABLE "public"."tbl_rbac_functions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tbl_rbac_functions_permissions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_function" bigint NOT NULL,
    "id_permission" bigint NOT NULL
);

ALTER TABLE "public"."tbl_rbac_functions_permissions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tbl_rbac_permissions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "permission" smallint[] NOT NULL
);

ALTER TABLE "public"."tbl_rbac_permissions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tbl_rbac_users_functions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" bigint NOT NULL,
    "id_function" bigint NOT NULL
);

ALTER TABLE "public"."tbl_rbac_users_functions" OWNER TO "postgres";

ALTER TABLE "public"."tbl_rbac_functions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_rbca_functions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."tbl_rbac_functions_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_rbca_functions_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."tbl_rbac_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_rbca_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."tbl_rbac_users_functions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_rbca_users_functions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_user" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user" "text" NOT NULL
);

ALTER TABLE "public"."tbl_users" OWNER TO "postgres";

ALTER TABLE "public"."tbl_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE OR REPLACE VIEW "public"."view_checklist_productlist" AS
SELECT
    NULL::bigint AS "checklist_id",
    NULL::timestamp with time zone AS "checklist_created_at",
    NULL::bigint AS "patient_id",
    NULL::bigint AS "doctor_id",
    NULL::bigint AS "user_id",
    NULL::smallint AS "checklist_status",
    NULL::"jsonb" AS "products",
    NULL::real AS "total_price";

ALTER TABLE "public"."view_checklist_productlist" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."view_permissions_users_functions" AS
 SELECT "au"."id" AS "id_user",
    "p"."permission"[1] AS "first",
    "p"."permission"[2] AS "second",
    "p"."permission"[3] AS "third",
    "p"."permission"[4] AS "fourth",
    "p"."permission"[5] AS "fifth",
    "p"."permission"[6] AS "sixth",
    "p"."permission"[7] AS "seventh",
    "p"."permission"[8] AS "eighth",
    "p"."permission"[9] AS "ninth",
    "p"."permission"[10] AS "tenth"
   FROM (((("auth"."users" "au"
     JOIN "public"."tbl_users" "u" ON (("au"."id" = "u"."id_user")))
     JOIN "public"."tbl_rbac_users_functions" "uf" ON (("u"."id" = "uf"."id_user")))
     JOIN "public"."tbl_rbac_functions_permissions" "fp" ON (("uf"."id_function" = "fp"."id_function")))
     JOIN "public"."tbl_rbac_permissions" "p" ON (("fp"."id_permission" = "p"."id")));

ALTER TABLE "public"."view_permissions_users_functions" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."view_products_purchase" AS
 SELECT "p"."product",
    "p"."amount",
    "p"."minimum",
    "p"."purchase",
    "p"."unit"
   FROM "public"."tbl_products" "p"
  WHERE ("p"."minimum" < "p"."amount");

ALTER TABLE "public"."view_products_purchase" OWNER TO "postgres";

ALTER TABLE ONLY "public"."tbl_allowed_domains"
    ADD CONSTRAINT "tbl_allowed_domains_domain_key" UNIQUE ("domain");

ALTER TABLE ONLY "public"."tbl_allowed_domains"
    ADD CONSTRAINT "tbl_allowed_domains_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_allowed_domains"
    ADD CONSTRAINT "tbl_allowed_domains_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "tbl_checklist_productlists_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "tbl_checklist_productlists_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "tbl_checklists_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "tbl_checklists_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_companies"
    ADD CONSTRAINT "tbl_companies_company_key" UNIQUE ("company");

ALTER TABLE ONLY "public"."tbl_companies"
    ADD CONSTRAINT "tbl_companies_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_companies"
    ADD CONSTRAINT "tbl_companies_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_doctors"
    ADD CONSTRAINT "tbl_doctors_doctor_key" UNIQUE ("doctor");

ALTER TABLE ONLY "public"."tbl_doctors"
    ADD CONSTRAINT "tbl_doctors_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_doctors"
    ADD CONSTRAINT "tbl_doctors_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_imported"
    ADD CONSTRAINT "tbl_imported_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_imported"
    ADD CONSTRAINT "tbl_imported_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_inventory"
    ADD CONSTRAINT "tbl_inventory_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_inventory"
    ADD CONSTRAINT "tbl_inventory_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_patients"
    ADD CONSTRAINT "tbl_patients_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_patients"
    ADD CONSTRAINT "tbl_patients_patient_key" UNIQUE ("patient");

ALTER TABLE ONLY "public"."tbl_patients"
    ADD CONSTRAINT "tbl_patients_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_percentages"
    ADD CONSTRAINT "tbl_percentages_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_percentages"
    ADD CONSTRAINT "tbl_percentages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_products"
    ADD CONSTRAINT "tbl_products_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_products"
    ADD CONSTRAINT "tbl_products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_products"
    ADD CONSTRAINT "tbl_products_product_key" UNIQUE ("product");

ALTER TABLE ONLY "public"."tbl_purchases"
    ADD CONSTRAINT "tbl_purchases_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_rbac_functions"
    ADD CONSTRAINT "tbl_rbca_functions_function_key" UNIQUE ("function");

ALTER TABLE ONLY "public"."tbl_rbac_functions_permissions"
    ADD CONSTRAINT "tbl_rbca_functions_permissions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_rbac_functions"
    ADD CONSTRAINT "tbl_rbca_functions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_rbac_permissions"
    ADD CONSTRAINT "tbl_rbca_permissions_permission_key" UNIQUE ("permission");

ALTER TABLE ONLY "public"."tbl_rbac_permissions"
    ADD CONSTRAINT "tbl_rbca_permissionss_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_rbac_users_functions"
    ADD CONSTRAINT "tbl_rbca_users_functions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_users"
    ADD CONSTRAINT "tbl_user_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tbl_users"
    ADD CONSTRAINT "tbl_user_id_user_key" UNIQUE ("id_user");

ALTER TABLE ONLY "public"."tbl_users"
    ADD CONSTRAINT "tbl_user_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_users"
    ADD CONSTRAINT "tbl_user_user_key" UNIQUE ("user");

CREATE OR REPLACE VIEW "public"."view_checklist_productlist" AS
 SELECT "cl"."id" AS "checklist_id",
    "cl"."created_at" AS "checklist_created_at",
    "cl"."id_patient" AS "patient_id",
    "cl"."id_doctor" AS "doctor_id",
    "cl"."id_user" AS "user_id",
    "cl"."status" AS "checklist_status",
    "jsonb_agg"("jsonb_build_object"('id_product', "cp"."id_product", 'amount', "cp"."amount", 'final_price', "cp"."final_price")) AS "products",
    "sum"("cp"."final_price") AS "total_price"
   FROM ("public"."tbl_checklists" "cl"
     LEFT JOIN ( SELECT "tbl_checklist_productlists"."id_checklist",
            "tbl_checklist_productlists"."id_product",
            "tbl_checklist_productlists"."amount",
            "tbl_checklist_productlists"."final_price"
           FROM "public"."tbl_checklist_productlists") "cp" ON (("cl"."id" = "cp"."id_checklist")))
  GROUP BY "cl"."id";

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "public_tbl_checklist_productlists_id_checklist_fkey" FOREIGN KEY ("id_checklist") REFERENCES "public"."tbl_checklists"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "public_tbl_checklist_productlists_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES "public"."tbl_products"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "public_tbl_checklists_id_doctor_fkey" FOREIGN KEY ("id_doctor") REFERENCES "public"."tbl_doctors"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "public_tbl_checklists_id_patient_fkey" FOREIGN KEY ("id_patient") REFERENCES "public"."tbl_patients"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_checklists"
    ADD CONSTRAINT "public_tbl_checklists_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."tbl_users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_inventory"
    ADD CONSTRAINT "public_tbl_inventory_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES "public"."tbl_products"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_inventory"
    ADD CONSTRAINT "public_tbl_inventory_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."tbl_users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_products"
    ADD CONSTRAINT "public_tbl_products_id_percentages_fkey" FOREIGN KEY ("id_percentages") REFERENCES "public"."tbl_percentages"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_purchases"
    ADD CONSTRAINT "public_tbl_purchases_id_company_fkey" FOREIGN KEY ("id_company") REFERENCES "public"."tbl_companies"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_purchases"
    ADD CONSTRAINT "public_tbl_purchases_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES "public"."tbl_products"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_purchases"
    ADD CONSTRAINT "public_tbl_purchases_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."tbl_users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_rbac_functions_permissions"
    ADD CONSTRAINT "public_tbl_rbca_functions_permissions_id_function_fkey" FOREIGN KEY ("id_function") REFERENCES "public"."tbl_rbac_functions"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_rbac_functions_permissions"
    ADD CONSTRAINT "public_tbl_rbca_functions_permissions_id_permission_fkey" FOREIGN KEY ("id_permission") REFERENCES "public"."tbl_rbac_permissions"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_rbac_users_functions"
    ADD CONSTRAINT "public_tbl_rbca_users_functions_id_function_fkey" FOREIGN KEY ("id_function") REFERENCES "public"."tbl_rbac_functions"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_rbac_users_functions"
    ADD CONSTRAINT "public_tbl_rbca_users_functions_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."tbl_users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."tbl_users"
    ADD CONSTRAINT "public_tbl_users_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_allowed_domains" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_checklist_productlists" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_checklists" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_companies" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_doctors" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_imported" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_inventory" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_patients" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_percentages" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_products" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_purchases" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_rbac_functions" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_rbac_functions_permissions" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_rbac_permissions" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_rbac_users_functions" TO "authenticated" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_users" TO "authenticated" USING (true);

ALTER TABLE "public"."tbl_allowed_domains" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_checklist_productlists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_checklists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_companies" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_doctors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_imported" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_inventory" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_patients" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_percentages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_products" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_purchases" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_rbac_functions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_rbac_functions_permissions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_rbac_permissions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_rbac_users_functions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_users" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "anon";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "anon";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_checklists" TO "anon";
GRANT ALL ON TABLE "public"."tbl_checklists" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_checklists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_checklists_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_companies" TO "anon";
GRANT ALL ON TABLE "public"."tbl_companies" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_companies" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_companies_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_doctors" TO "anon";
GRANT ALL ON TABLE "public"."tbl_doctors" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_doctors" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_doctors_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_imported" TO "anon";
GRANT ALL ON TABLE "public"."tbl_imported" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_imported" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_imported_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_inventory" TO "anon";
GRANT ALL ON TABLE "public"."tbl_inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_inventory" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_inventory_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_patients" TO "anon";
GRANT ALL ON TABLE "public"."tbl_patients" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_patients" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_patients_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_percentages" TO "anon";
GRANT ALL ON TABLE "public"."tbl_percentages" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_percentages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_percentages_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_products" TO "anon";
GRANT ALL ON TABLE "public"."tbl_products" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_purchases" TO "anon";
GRANT ALL ON TABLE "public"."tbl_purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_purchases" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_purchases_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_rbac_functions" TO "anon";
GRANT ALL ON TABLE "public"."tbl_rbac_functions" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_rbac_functions" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_rbac_functions_permissions" TO "anon";
GRANT ALL ON TABLE "public"."tbl_rbac_functions_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_rbac_functions_permissions" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_rbac_permissions" TO "anon";
GRANT ALL ON TABLE "public"."tbl_rbac_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_rbac_permissions" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_rbac_users_functions" TO "anon";
GRANT ALL ON TABLE "public"."tbl_rbac_users_functions" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_rbac_users_functions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_functions_permissions_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_rbca_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_permissions_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_rbca_users_functions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_users_functions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_rbca_users_functions_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_users" TO "anon";
GRANT ALL ON TABLE "public"."tbl_users" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_users" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_user_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."view_checklist_productlist" TO "anon";
GRANT ALL ON TABLE "public"."view_checklist_productlist" TO "authenticated";
GRANT ALL ON TABLE "public"."view_checklist_productlist" TO "service_role";

GRANT ALL ON TABLE "public"."view_permissions_users_functions" TO "anon";
GRANT ALL ON TABLE "public"."view_permissions_users_functions" TO "authenticated";
GRANT ALL ON TABLE "public"."view_permissions_users_functions" TO "service_role";

GRANT ALL ON TABLE "public"."view_products_purchase" TO "anon";
GRANT ALL ON TABLE "public"."view_products_purchase" TO "authenticated";
GRANT ALL ON TABLE "public"."view_products_purchase" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
