
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."tbl_allowed_domains" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "domain" "text"
);

ALTER TABLE "public"."tbl_allowed_domains" OWNER TO "postgres";

ALTER TABLE "public"."tbl_allowed_domains" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_allowed_domains_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tbl_checklist_productlists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_checklist" bigint,
    "id_product" bigint,
    "amount" integer,
    "final_price" real
);

ALTER TABLE "public"."tbl_checklist_productlists" OWNER TO "postgres";

ALTER TABLE "public"."tbl_checklist_productlists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tbl_checklist_productlists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."tbl_allowed_domains"
    ADD CONSTRAINT "tbl_allowed_domains_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tbl_checklist_productlists"
    ADD CONSTRAINT "tbl_checklist_productlists_pkey" PRIMARY KEY ("id");

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_allowed_domains" USING (true);

CREATE POLICY "Policy with security definer functions" ON "public"."tbl_checklist_productlists" TO "authenticated" USING (true);

ALTER TABLE "public"."tbl_allowed_domains" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tbl_checklist_productlists" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "anon";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_allowed_domains" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_allowed_domains_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "anon";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "authenticated";
GRANT ALL ON TABLE "public"."tbl_checklist_productlists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tbl_checklist_productlists_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;

--
-- Dumped schema changes for auth and storage
--

