create table "public"."tbl_companies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "company" text not null
);


create table "public"."tbl_doctors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "doctor" text not null
);


create table "public"."tbl_imported" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "doctor" text not null,
    "patient" text not null,
    "date" date not null,
    "value" real not null,
    "health_insurance" text not null,
    "description" text not null,
    "month" smallint not null,
    "year" smallint not null,
    "payment_method" smallint,
    "card_fee" real
);


create table "public"."tbl_inventory" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "id_user" bigint not null,
    "id_product" bigint not null,
    "type" smallint not null,
    "amount" integer not null,
    "reason" smallint not null
);


create table "public"."tbl_patients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "patient" text not null
);


create table "public"."tbl_percentages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "administration" real not null,
    "basic_taxes" jsonb[]
);


create table "public"."tbl_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "id_percentages" bigint not null,
    "product" text not null,
    "type" smallint not null,
    "unit" text not null,
    "base_price" real not null,
    "minimum" integer not null,
    "purchase" integer not null
);


create table "public"."tbl_purchases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "id_user" bigint not null,
    "id_company" bigint not null,
    "id_product" bigint not null,
    "amount" integer not null,
    "price" real not null,
    "taxes" jsonb
);


create table "public"."tbl_user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "id_user" bigint not null,
    "user" text not null
);


alter table "public"."tbl_checklists" alter column "id_user" set not null;

CREATE UNIQUE INDEX tbl_companies_company_key ON public.tbl_companies USING btree (company);

CREATE UNIQUE INDEX tbl_companies_pkey ON public.tbl_companies USING btree (id);

CREATE UNIQUE INDEX tbl_doctors_doctor_key ON public.tbl_doctors USING btree (doctor);

CREATE UNIQUE INDEX tbl_doctors_pkey ON public.tbl_doctors USING btree (id);

CREATE UNIQUE INDEX tbl_imported_id_key ON public.tbl_imported USING btree (id);

CREATE UNIQUE INDEX tbl_imported_pkey ON public.tbl_imported USING btree (id);

CREATE UNIQUE INDEX tbl_inventory_pkey ON public.tbl_inventory USING btree (id);

CREATE UNIQUE INDEX tbl_patients_pkey ON public.tbl_patients USING btree (id);

CREATE UNIQUE INDEX tbl_percentages_pkey ON public.tbl_percentages USING btree (id);

CREATE UNIQUE INDEX tbl_products_pkey ON public.tbl_products USING btree (id);

CREATE UNIQUE INDEX tbl_purchases_pkey ON public.tbl_purchases USING btree (id);

CREATE UNIQUE INDEX tbl_user_id_key ON public.tbl_user USING btree (id);

CREATE UNIQUE INDEX tbl_user_id_user_key ON public.tbl_user USING btree (id_user);

CREATE UNIQUE INDEX tbl_user_pkey ON public.tbl_user USING btree (id);

alter table "public"."tbl_companies" add constraint "tbl_companies_pkey" PRIMARY KEY using index "tbl_companies_pkey";

alter table "public"."tbl_doctors" add constraint "tbl_doctors_pkey" PRIMARY KEY using index "tbl_doctors_pkey";

alter table "public"."tbl_imported" add constraint "tbl_imported_pkey" PRIMARY KEY using index "tbl_imported_pkey";

alter table "public"."tbl_inventory" add constraint "tbl_inventory_pkey" PRIMARY KEY using index "tbl_inventory_pkey";

alter table "public"."tbl_patients" add constraint "tbl_patients_pkey" PRIMARY KEY using index "tbl_patients_pkey";

alter table "public"."tbl_percentages" add constraint "tbl_percentages_pkey" PRIMARY KEY using index "tbl_percentages_pkey";

alter table "public"."tbl_products" add constraint "tbl_products_pkey" PRIMARY KEY using index "tbl_products_pkey";

alter table "public"."tbl_purchases" add constraint "tbl_purchases_pkey" PRIMARY KEY using index "tbl_purchases_pkey";

alter table "public"."tbl_user" add constraint "tbl_user_pkey" PRIMARY KEY using index "tbl_user_pkey";

alter table "public"."tbl_companies" add constraint "tbl_companies_company_key" UNIQUE using index "tbl_companies_company_key";

alter table "public"."tbl_doctors" add constraint "tbl_doctors_doctor_key" UNIQUE using index "tbl_doctors_doctor_key";

alter table "public"."tbl_imported" add constraint "tbl_imported_id_key" UNIQUE using index "tbl_imported_id_key";

alter table "public"."tbl_user" add constraint "tbl_user_id_key" UNIQUE using index "tbl_user_id_key";

alter table "public"."tbl_user" add constraint "tbl_user_id_user_key" UNIQUE using index "tbl_user_id_user_key";

grant delete on table "public"."tbl_companies" to "anon";

grant insert on table "public"."tbl_companies" to "anon";

grant references on table "public"."tbl_companies" to "anon";

grant select on table "public"."tbl_companies" to "anon";

grant trigger on table "public"."tbl_companies" to "anon";

grant truncate on table "public"."tbl_companies" to "anon";

grant update on table "public"."tbl_companies" to "anon";

grant delete on table "public"."tbl_companies" to "authenticated";

grant insert on table "public"."tbl_companies" to "authenticated";

grant references on table "public"."tbl_companies" to "authenticated";

grant select on table "public"."tbl_companies" to "authenticated";

grant trigger on table "public"."tbl_companies" to "authenticated";

grant truncate on table "public"."tbl_companies" to "authenticated";

grant update on table "public"."tbl_companies" to "authenticated";

grant delete on table "public"."tbl_companies" to "service_role";

grant insert on table "public"."tbl_companies" to "service_role";

grant references on table "public"."tbl_companies" to "service_role";

grant select on table "public"."tbl_companies" to "service_role";

grant trigger on table "public"."tbl_companies" to "service_role";

grant truncate on table "public"."tbl_companies" to "service_role";

grant update on table "public"."tbl_companies" to "service_role";

grant delete on table "public"."tbl_doctors" to "anon";

grant insert on table "public"."tbl_doctors" to "anon";

grant references on table "public"."tbl_doctors" to "anon";

grant select on table "public"."tbl_doctors" to "anon";

grant trigger on table "public"."tbl_doctors" to "anon";

grant truncate on table "public"."tbl_doctors" to "anon";

grant update on table "public"."tbl_doctors" to "anon";

grant delete on table "public"."tbl_doctors" to "authenticated";

grant insert on table "public"."tbl_doctors" to "authenticated";

grant references on table "public"."tbl_doctors" to "authenticated";

grant select on table "public"."tbl_doctors" to "authenticated";

grant trigger on table "public"."tbl_doctors" to "authenticated";

grant truncate on table "public"."tbl_doctors" to "authenticated";

grant update on table "public"."tbl_doctors" to "authenticated";

grant delete on table "public"."tbl_doctors" to "service_role";

grant insert on table "public"."tbl_doctors" to "service_role";

grant references on table "public"."tbl_doctors" to "service_role";

grant select on table "public"."tbl_doctors" to "service_role";

grant trigger on table "public"."tbl_doctors" to "service_role";

grant truncate on table "public"."tbl_doctors" to "service_role";

grant update on table "public"."tbl_doctors" to "service_role";

grant delete on table "public"."tbl_imported" to "anon";

grant insert on table "public"."tbl_imported" to "anon";

grant references on table "public"."tbl_imported" to "anon";

grant select on table "public"."tbl_imported" to "anon";

grant trigger on table "public"."tbl_imported" to "anon";

grant truncate on table "public"."tbl_imported" to "anon";

grant update on table "public"."tbl_imported" to "anon";

grant delete on table "public"."tbl_imported" to "authenticated";

grant insert on table "public"."tbl_imported" to "authenticated";

grant references on table "public"."tbl_imported" to "authenticated";

grant select on table "public"."tbl_imported" to "authenticated";

grant trigger on table "public"."tbl_imported" to "authenticated";

grant truncate on table "public"."tbl_imported" to "authenticated";

grant update on table "public"."tbl_imported" to "authenticated";

grant delete on table "public"."tbl_imported" to "service_role";

grant insert on table "public"."tbl_imported" to "service_role";

grant references on table "public"."tbl_imported" to "service_role";

grant select on table "public"."tbl_imported" to "service_role";

grant trigger on table "public"."tbl_imported" to "service_role";

grant truncate on table "public"."tbl_imported" to "service_role";

grant update on table "public"."tbl_imported" to "service_role";

grant delete on table "public"."tbl_inventory" to "anon";

grant insert on table "public"."tbl_inventory" to "anon";

grant references on table "public"."tbl_inventory" to "anon";

grant select on table "public"."tbl_inventory" to "anon";

grant trigger on table "public"."tbl_inventory" to "anon";

grant truncate on table "public"."tbl_inventory" to "anon";

grant update on table "public"."tbl_inventory" to "anon";

grant delete on table "public"."tbl_inventory" to "authenticated";

grant insert on table "public"."tbl_inventory" to "authenticated";

grant references on table "public"."tbl_inventory" to "authenticated";

grant select on table "public"."tbl_inventory" to "authenticated";

grant trigger on table "public"."tbl_inventory" to "authenticated";

grant truncate on table "public"."tbl_inventory" to "authenticated";

grant update on table "public"."tbl_inventory" to "authenticated";

grant delete on table "public"."tbl_inventory" to "service_role";

grant insert on table "public"."tbl_inventory" to "service_role";

grant references on table "public"."tbl_inventory" to "service_role";

grant select on table "public"."tbl_inventory" to "service_role";

grant trigger on table "public"."tbl_inventory" to "service_role";

grant truncate on table "public"."tbl_inventory" to "service_role";

grant update on table "public"."tbl_inventory" to "service_role";

grant delete on table "public"."tbl_patients" to "anon";

grant insert on table "public"."tbl_patients" to "anon";

grant references on table "public"."tbl_patients" to "anon";

grant select on table "public"."tbl_patients" to "anon";

grant trigger on table "public"."tbl_patients" to "anon";

grant truncate on table "public"."tbl_patients" to "anon";

grant update on table "public"."tbl_patients" to "anon";

grant delete on table "public"."tbl_patients" to "authenticated";

grant insert on table "public"."tbl_patients" to "authenticated";

grant references on table "public"."tbl_patients" to "authenticated";

grant select on table "public"."tbl_patients" to "authenticated";

grant trigger on table "public"."tbl_patients" to "authenticated";

grant truncate on table "public"."tbl_patients" to "authenticated";

grant update on table "public"."tbl_patients" to "authenticated";

grant delete on table "public"."tbl_patients" to "service_role";

grant insert on table "public"."tbl_patients" to "service_role";

grant references on table "public"."tbl_patients" to "service_role";

grant select on table "public"."tbl_patients" to "service_role";

grant trigger on table "public"."tbl_patients" to "service_role";

grant truncate on table "public"."tbl_patients" to "service_role";

grant update on table "public"."tbl_patients" to "service_role";

grant delete on table "public"."tbl_percentages" to "anon";

grant insert on table "public"."tbl_percentages" to "anon";

grant references on table "public"."tbl_percentages" to "anon";

grant select on table "public"."tbl_percentages" to "anon";

grant trigger on table "public"."tbl_percentages" to "anon";

grant truncate on table "public"."tbl_percentages" to "anon";

grant update on table "public"."tbl_percentages" to "anon";

grant delete on table "public"."tbl_percentages" to "authenticated";

grant insert on table "public"."tbl_percentages" to "authenticated";

grant references on table "public"."tbl_percentages" to "authenticated";

grant select on table "public"."tbl_percentages" to "authenticated";

grant trigger on table "public"."tbl_percentages" to "authenticated";

grant truncate on table "public"."tbl_percentages" to "authenticated";

grant update on table "public"."tbl_percentages" to "authenticated";

grant delete on table "public"."tbl_percentages" to "service_role";

grant insert on table "public"."tbl_percentages" to "service_role";

grant references on table "public"."tbl_percentages" to "service_role";

grant select on table "public"."tbl_percentages" to "service_role";

grant trigger on table "public"."tbl_percentages" to "service_role";

grant truncate on table "public"."tbl_percentages" to "service_role";

grant update on table "public"."tbl_percentages" to "service_role";

grant delete on table "public"."tbl_products" to "anon";

grant insert on table "public"."tbl_products" to "anon";

grant references on table "public"."tbl_products" to "anon";

grant select on table "public"."tbl_products" to "anon";

grant trigger on table "public"."tbl_products" to "anon";

grant truncate on table "public"."tbl_products" to "anon";

grant update on table "public"."tbl_products" to "anon";

grant delete on table "public"."tbl_products" to "authenticated";

grant insert on table "public"."tbl_products" to "authenticated";

grant references on table "public"."tbl_products" to "authenticated";

grant select on table "public"."tbl_products" to "authenticated";

grant trigger on table "public"."tbl_products" to "authenticated";

grant truncate on table "public"."tbl_products" to "authenticated";

grant update on table "public"."tbl_products" to "authenticated";

grant delete on table "public"."tbl_products" to "service_role";

grant insert on table "public"."tbl_products" to "service_role";

grant references on table "public"."tbl_products" to "service_role";

grant select on table "public"."tbl_products" to "service_role";

grant trigger on table "public"."tbl_products" to "service_role";

grant truncate on table "public"."tbl_products" to "service_role";

grant update on table "public"."tbl_products" to "service_role";

grant delete on table "public"."tbl_purchases" to "anon";

grant insert on table "public"."tbl_purchases" to "anon";

grant references on table "public"."tbl_purchases" to "anon";

grant select on table "public"."tbl_purchases" to "anon";

grant trigger on table "public"."tbl_purchases" to "anon";

grant truncate on table "public"."tbl_purchases" to "anon";

grant update on table "public"."tbl_purchases" to "anon";

grant delete on table "public"."tbl_purchases" to "authenticated";

grant insert on table "public"."tbl_purchases" to "authenticated";

grant references on table "public"."tbl_purchases" to "authenticated";

grant select on table "public"."tbl_purchases" to "authenticated";

grant trigger on table "public"."tbl_purchases" to "authenticated";

grant truncate on table "public"."tbl_purchases" to "authenticated";

grant update on table "public"."tbl_purchases" to "authenticated";

grant delete on table "public"."tbl_purchases" to "service_role";

grant insert on table "public"."tbl_purchases" to "service_role";

grant references on table "public"."tbl_purchases" to "service_role";

grant select on table "public"."tbl_purchases" to "service_role";

grant trigger on table "public"."tbl_purchases" to "service_role";

grant truncate on table "public"."tbl_purchases" to "service_role";

grant update on table "public"."tbl_purchases" to "service_role";

grant delete on table "public"."tbl_user" to "anon";

grant insert on table "public"."tbl_user" to "anon";

grant references on table "public"."tbl_user" to "anon";

grant select on table "public"."tbl_user" to "anon";

grant trigger on table "public"."tbl_user" to "anon";

grant truncate on table "public"."tbl_user" to "anon";

grant update on table "public"."tbl_user" to "anon";

grant delete on table "public"."tbl_user" to "authenticated";

grant insert on table "public"."tbl_user" to "authenticated";

grant references on table "public"."tbl_user" to "authenticated";

grant select on table "public"."tbl_user" to "authenticated";

grant trigger on table "public"."tbl_user" to "authenticated";

grant truncate on table "public"."tbl_user" to "authenticated";

grant update on table "public"."tbl_user" to "authenticated";

grant delete on table "public"."tbl_user" to "service_role";

grant insert on table "public"."tbl_user" to "service_role";

grant references on table "public"."tbl_user" to "service_role";

grant select on table "public"."tbl_user" to "service_role";

grant trigger on table "public"."tbl_user" to "service_role";

grant truncate on table "public"."tbl_user" to "service_role";

grant update on table "public"."tbl_user" to "service_role";


