name: Push from Supabase

on:
  # Defina os eventos que devem acionar o workflow, por exemplo, quando uma alteração é feita no banco de dados no Supabase
  push:
    branches:
      - main # Substitua pelo nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo para clonar o repositório do GitHub onde você deseja fazer o push
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Passo para instalar o Supabase CLI
      - name: Install Supabase CLI
        run: npm install -g supabase-cli # Ou o método que você usa para instalar o Supabase CLI

      # Passo para configurar as credenciais do Supabase
      - name: Setup Supabase CLI
        run: |
          echo "url: ${{ secrets.SUPABASE_URL }}" > .supabasecli
          echo "key: ${{ secrets.SUPABASE_KEY }}" >> .supabasecli
      # Passo para executar o comando Supabase para fazer o push
      - name: Push to GitHub from Supabase
        run: |
          supabase migrate up
