name: Push from Supabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      
    steps:

            # Passo para fazer o commit e push das alterações para o GitHub
      - name: Commit and push changes
        run: |
          git config --global user.email "conradoacarvalho@gmail.com"
          git config --global user.name "Golduro"
          git add .
          git commit -m "Push from Supabase"
          git push origin main
